---
title: "PHC6791_SGP_Spatial Mapping"
author: "Rylen Garlitz"
date: '`r Sys.Date()`'
output: html_document
---

libraries
```{r}
library(tidyverse)
library(tidygeocoder)
library(sf)
#library(rnaturalearth)
#library(rnaturalearthdata)
library(maps)
library(leaflet) #Interactive Map Plotting
#install.packages("leaflegend")
library(leaflegend)
library(osrm) #Routing

```


Read in some shit
```{r}
markets <-read.csv("data/SNAP Retailer Location data.csv")
str(markets)

markets$Store.Type <- as.factor(markets$Store.Type)

levels(markets$Store.Type)

markets.sf <- st_as_sf(markets, coords = c("Longitude", "Latitude"), crs = st_crs(4326))
```


## Creating Interactive Spatial Map
```{r}
(map <- leaflet(data = markets) %>% 
  addTiles() %>% 
  addMarkers(lng = markets$Longitude, lat = markets$Latitude, popup = markets$Store.Name))

#Select Points
CircleK2721002 <- markets %>% 
  filter(Store.Name == "Circle K 2721002") %>% 
  select(Longitude, Latitude)

CVS4629 <- markets %>% 
  filter(Store.Name == "CVS Pharmacy 4629") %>% 
  select(Longitude, Latitude)

#Create Dataframe of Coordinates
CVs_CircleK <- data.frame(rbind(CircleK2721002, CVS4629))

#Create Route information
CVS_CircleK.route <- osrmRoute(loc = CVs_CircleK)
CVS_CircleK.route
#20.02 km from points.

#Plot Route Data
(map <- leaflet(data = markets) %>% 
  addTiles() %>% 
  addMarkers(lng = markets$Longitude, lat = markets$Latitude, popup = markets$Store.Name, icon = store.icons[markets$Icons]))


markets$Icons <- unlist(markets$Icons)
```


## Shelters

```{r}
shelters <- read.csv("data/FL508_CoC_Addresses.csv")


shelters.GV <- shelters %>% 
 filter(CoC == "Gainesville/Alachua, Putnam Counties CoC") #Filter Gainesville/Alachua, Putnam Counties

unique(shelters.GV$Organization.Name)  # How many Shelters?

shelters.GV <- shelters.GV %>% 
  distinct(Organization.Name, .keep_all = T) #Remove duplicate names.

#Add Data
shelters.GV <- shelters.GV[-c(1),]

shelters.GV[2,16] <- "926 St. Johns Ave"
shelters.GV[2,17] <- "Palatka"

shelters.GV[3,16] <- "2100 NW 53rd Ave"
shelters.GV[3,17] <- "Gainesville"

shelters.GV[4,16] <- "1810 NW 6th St"

shelters.GV[11,16] <- "1405 NW 13th St"

shelters.GV[14,16] <- "2130 NW 31st Ave"

shelters.GV <- shelters.GV %>% 
  mutate(address = paste(address1, city, state, zip, sep = ","))
```


## Geocode Shelters
```{r}
geo.shelters <- shelters.GV %>% 
  geocode(address = address, method = "osm")


geo.shelters.sf <- st_as_sf(geo.shelters, coords = c("long", 'lat'), na.fail = F)

#write_sf(geo.shelters.sf, "data/geo.shelters.csv")
```


## Plot Shelters
```{r}
leaflet(geo.shelters.sf) %>% 
  addProviderTiles("CartoDB.Positron") %>% 
  addAwesomeMarkers(data = geo.shelters.sf, popup = geo.shelters.sf$Organization.Name)
```

## Bus Data

```{r}
bus.stops <- read_sf("data/RTSBusStops_Spring2024", layer = "RTSBusStops_Fall2023")
bus.stops

bus.stops <- bus.stops %>% 
  filter(!OBJECTID == "0")

bus.stops <- bus.stops %>% 
  st_transform('+proj=longlat +datum=WGS84')

(bus.stop.map <- leaflet(data = bus.stops) %>% 
  addTiles() %>% 
  addCircleMarkers(lng = bus.stops$LONGITUDE, lat = bus.stops$LATITUDE, popup = bus.stops$STOP_NAME, radius = 0.5, fillOpacity = 1, color = "black"))

bus.routes <- st_read("data/RTSBusRoutes_Spring2024") %>% 
  st_transform('+proj=longlat +datum=WGS84')

head(bus.routes)

#Test Plotting LINESTRING
plot(st_geometry(bus.routes))

leaflet(bus.routes) %>% 
  addProviderTiles("CartoDB.Positron") %>% 
  addPolylines(data = bus.routes, opacity = 1, color = "purple", label = bus.routes$route_id, weight = 2) %>% 
  addCircleMarkers(lng = bus.stops$LONGITUDE, lat = bus.stops$LATITUDE, popup = bus.stops$STOP_NAME, weight = 1, radius = 2, fillOpacity = 1) %>% 
  addCircleMarkers(lng = markets$Longitude, lat = markets$Latitude, popup = markets$Store.Name, weight = 2, radius = 4, fillOpacity = 1, color = "red")
```

### Change the Icons

```{r}

library(fontawesome)

markets.sf <- markets.sf %>% 
  mutate(Icons = case_when(
    Store.Type == "Supermarket" ~ "Supermarket", 
    Store.Type == "Convenience Store" ~ "ConvenienceStore", 
    Store.Type == "Farmers and Markets" ~ "FarmersMarket", 
    Store.Type == "Grocery Store" ~ "Grocery", 
    Store.Type == "Super Store" ~ "SuperStore", 
    Store.Type == "Specialty Store" ~ "Specialty", 
    Store.Type == "Other" ~ "Other"
  ))

markets.sf$Icons <- as.factor(markets.sf$Icons)
levels(markets.sf$Icons)


store.icons <- awesomeIconList(
  Supermarket = makeAwesomeIcon(
    icon = "shopping-cart", 
    markerColor = "lightred", 
    library= "fa"
  ),
  ConvenienceStore = makeAwesomeIcon(
    icon = "pizza", 
    iconColor = "black",
    markerColor = "blue", 
    library = "ion"
  ), 
  FarmersMarket = makeAwesomeIcon(
    icon = "group",
    markerColor = "green", 
    library = "fa"
  ), 
  Grocery = makeAwesomeIcon(
    icon = "shopping-basket", 
    markerColor = "pink", 
    library = "fa"
  ), 
  SuperStore = makeAwesomeIcon(
    icon = "cubes", 
    markerColor = "purple", 
    library = "fa"
  ), 
  Specialty = makeAwesomeIcon(
    icon = "info", 
    markerColor = "lightgray", 
    library = "fa"
  ), 
  Other = makeAwesomeIcon(
    icon = "asterisk", 
    markerColor = "orange", 
    library = "fa"
  )
)

shelter.icon <- makeAwesomeIcon(
  icon = "home", 
  iconColor = "black", 
  markerColor = "red", 
  library = "fa"
)

bus.route.colors <- colorFactor(c("#0D479C",
"#10D3DE",
"#04109A",
"#83D5FD",
"#7F1F4A",
"#6FE329",
"#50CBE7",
"#5A19A6",
"#641D60",
"#3529D6",
"#EF6DD0",
"#7A54BE",
"#B01ECC",
"#F2A5FA",
"#4BCE4A",
"#84F22B",
"#8B618C",
"#48C880",
"#5C4DAE",
"#AE0C0D",
"#FC0AF2",
"#4973A4",
"#B5EFC3",
"#749B5D",
"#03A747"), bus.routes$route_id)

```


Plot the Full Map
```{r} 
leaflet(markets.sf) %>% 
  addProviderTiles("CartoDB.Positron") %>% 
  addAwesomeMarkers(icon = ~store.icons[Icons],
                   label = ~as.character(Store.Name, Store.Type), 
                   group = "Stores") %>% #EBT/SNAP Markets
  addLegendAwesomeIcon(iconSet = store.icons, 
                       title = "Store Types",
                       position = "topright", 
                       group = "Stores") %>% 
  addAwesomeMarkers(data = geo.shelters.sf, 
                    popup = paste0(
                      "<b>Organization: </b>", 
                      geo.shelters.sf$Organization.Name, 
                      "<br>", 
                      "<b>Address: </b>", 
                      geo.shelters.sf$address1
                    ), 
                    icon = shelter.icon, group = "Shelters") %>% #Shelters
  addPolylines(data = bus.routes, 
               opacity = 1,
               popup = paste0(
                     "<b>Route: </b>", 
                     bus.routes$shape_id, 
                     "<br>",
                     "<b>Line: </b>", 
                     bus.routes$route_long
                   ), 
               label = bus.routes$route_id,
               weight = 3,
               group = "Bus Routes", color = ~bus.route.colors(route_id)) %>%  #Bus Routes
  #addLegendFactor(pal = bus.route.colors, values = bus.routes$route_id, group = "Bus Routes", position = "bottomleft" , orientation = "horizontal") %>% #Legend for Bus Routes
  addCircleMarkers(lng = bus.stops$LONGITUDE, 
                   lat = bus.stops$LATITUDE, 
                   popup = paste0(
                     "<b>Stop: </b>", 
                     bus.stops$STOP_NAME, 
                     "<br>",
                     "<b>Line: </b>", 
                     bus.stops$DESCRIPTIO
                   ),
                   radius = 4, 
                   opacity = 1,
                   stroke = F,
                   fillOpacity = 1,
                   color = "darkgrey",
                   group = "Bus Stops") %>% #Bus Stops
  addLayersControl(overlayGroups = c("Shelters","Stores","Bus Routes","Bus Stops"), position = "topleft", options = layersControlOptions(collapsed = F)) #Filter
       


                   
```

#Plotting Specific Routes

### Line 25/26 Inbound.
```{r}

GRACE <- geo.shelters.sf[c(5),]

walmart3877 <- markets.sf[c(82),]

#Create Dataframe of Coordinates
Grace_walmart3877 <- data.frame(rbind(GRACE, walmart3877))

#Create Route information
GRACE_walmart3877.route <- osrmRoute(dst = walmart3877, src = GRACE)

leaflet(data = markets.sf) %>% 
  addProviderTiles("CartoDB.Positron") %>% 
  #setView(lng = -82.30367, lat = 29.66646,zoom = 13) %>%
  addAwesomeMarkers(data = markets.sf[c(22,63, 72, 82,124,139,143, 144,148, 180,196, 203, 227),], icon = ~store.icons[Icons],
                   popup = ~as.character(Store.Street.Address), 
                   label = ~as.character(Store.Name),
                   group = "Stores") %>%
  addAwesomeMarkers(data = GRACE, 
                    popup = paste0(
                      "<b>Organization: </b>", 
                      GRACE$Organization.Name, 
                      "<br>", 
                      "<b>Address: </b>", 
                      GRACE$address1
                    ), 
                    icon = shelter.icon, group = "Shelters") %>%
  #addPolylines(data = GRACE_walmart3877.route, color = "red") %>% 
  addPolylines(data = bus.routes[c(75, 76),], 
               opacity = 1,
               popup = paste0(
                     "<b>Route: </b>", 
                     bus.routes[c(75, 76),]$shape_id, 
                     "<br>",
                     "<b>Line: </b>", 
                     bus.routes[c(75, 76),]$route_long
                   ), 
               label = ~as.character(route_id),
               weight = 3,
               group = "Bus Routes", color = "#03A747") %>% 
  addPolylines(data = bus.routes[c(10,11),], 
               opacity = 1,
               popup = paste0(
                     "<b>Route: </b>", 
                     bus.routes[c(10,11),]$shape_id, 
                     "<br>",
                     "<b>Line: </b>", 
                     bus.routes[c(10,11),]$route_long
                   ), 
               label = bus.routes[c(10,11),]$route_id,
               weight = 3,
               group = "Bus Routes", color = "#3529D6") %>% 
    addCircleMarkers(data = bus.stops[c(323, 892),],
                   popup = paste0(
                     "<b>Stop: </b>", 
                     bus.stops[c(323, 892),]$STOP_NAME, 
                     "<br>",
                     "<b>Line: </b>", 
                     bus.stops[c(323, 892),]$DESCRIPTIO
                   ),
                   radius = 4, 
                   opacity = 1,
                   stroke = F,
                   fillOpacity = 1,
                   color = "darkred",
                   group = "Bus Stops")
```

## Line 8/6
```{r}
leaflet(data = markets.sf) %>% 
  addProviderTiles("CartoDB.Positron") %>% 
  #setView(lng = -82.30367, lat = 29.66646,zoom = 13) %>%
  addAwesomeMarkers(data = markets.sf[c(10, 36,42,113,134,156,158,169,188,190, 194,195,196,198, 203,209, 212),], icon = ~store.icons[Icons],
                   popup = ~as.character(Store.Street.Address), 
                   label = ~as.character(Store.Name),
                   group = "Stores") %>%
  addAwesomeMarkers(data = geo.shelters.sf[c(3,9,4,11, 12,1,14),], 
                    popup = paste0(
                      "<b>Organization: </b>", 
                      GRACE$Organization.Name, 
                      "<br>", 
                      "<b>Address: </b>", 
                      GRACE$address1
                    ), 
                    icon = shelter.icon, group = "Shelters") %>%
  addPolylines(data = bus.routes[c(17,31),], 
               opacity = 1,
               popup = paste0(
                     "<b>Route: </b>", 
                     bus.routes[c(17,31),]$shape_id, 
                     "<br>",
                     "<b>Line: </b>", 
                     bus.routes[c(17,31),]$route_long
                   ), 
               label = ~as.character(route_id),
               weight = 3,
               group = "Bus Routes", color = "#03A747") %>% 
  addPolylines(data = bus.routes[c(19,49),], 
               opacity = 1,
               popup = paste0(
                     "<b>Route: </b>", 
                     bus.routes[c(19,49),]$shape_id, 
                     "<br>",
                     "<b>Line: </b>", 
                     bus.routes[c(19,49),]$route_long
                   ), 
               label = bus.routes[c(19,49),]$route_id,
               weight = 3,
               group = "Bus Routes", color = "#3529D6") %>% 
    addCircleMarkers(data = bus.stops[c(12),],
                   popup = paste0(
                     "<b>Stop: </b>", 
                     bus.stops[c(12),]$STOP_NAME, 
                     "<br>",
                     "<b>Line: </b>", 
                     bus.stops[c(12),]$DESCRIPTIO
                   ),
                   radius = 4, 
                   opacity = 1,
                   stroke = F,
                   fillOpacity = 1,
                   color = "darkred",
                   group = "Bus Stops")
```







